lecturers = {
    "Амирзянов Рашид Маратович": "https://www.ugrasu.ru/timetable/lecturer/6271",
    "Антонович Владимир Александрович": "https://www.ugrasu.ru/timetable/lecturer/8896",
    "Арапова-Дедович Екатерина Антоновна": "https://www.ugrasu.ru/timetable/lecturer/5901",
    "Аюпова Илюза Каюмовна": "https://www.ugrasu.ru/timetable/lecturer/10059",
    "Березин Евгений Владимирович": "https://www.ugrasu.ru/timetable/lecturer/6275",
    "Булыгин Константин Сергеевич": "https://www.ugrasu.ru/timetable/lecturer/5854",
    "Власова Лариса Михайловна": "https://www.ugrasu.ru/timetable/lecturer/8897",
    "Волоцков Дмитрий Викторович": "https://www.ugrasu.ru/timetable/lecturer/5867",
    "Галиев Рустам Рафидович": "https://www.ugrasu.ru/timetable/lecturer/8509",
    "Гамидуллаева Муминат Фажидиновна": "https://www.ugrasu.ru/timetable/lecturer/5896",
    "Гарбар Олег Викторович": "https://www.ugrasu.ru/timetable/lecturer/6250",
    "Гончаров Александр Владимирович": "https://www.ugrasu.ru/timetable/lecturer/9240",
    "Гоц Владимир Алексеевич": "https://www.ugrasu.ru/timetable/lecturer/5866",
    "Давлетбаева Гульназира Раиловна": "https://www.ugrasu.ru/timetable/lecturer/5802",
    "Дедков Роман Викторович": "https://www.ugrasu.ru/timetable/lecturer/5739",
    "Демидкина Ксения Сергеевна": "https://www.ugrasu.ru/timetable/lecturer/5477",
    "Деулина Светлана Леонидовна": "https://www.ugrasu.ru/timetable/lecturer/3996",
    "Джабраилов Магомед Сапарбекович": "https://www.ugrasu.ru/timetable/lecturer/5478",
    "Жернакова Оксана Васильевна": "https://www.ugrasu.ru/timetable/lecturer/6270",
    "Жибуляк Елена Сергеевна": "https://www.ugrasu.ru/timetable/lecturer/6252",
    "Зинатулин Владимир Нурисламович": "https://www.ugrasu.ru/timetable/lecturer/8741",
    "Игнатенко Виктор Николаевич": "https://www.ugrasu.ru/timetable/lecturer/9539",
    "Игнатенко Екатерина Сергеевна": "https://www.ugrasu.ru/timetable/lecturer/5828",
    "Ильяш Алексей Николаевич": "https://www.ugrasu.ru/timetable/lecturer/5879",
    "Кирилин Алексей Анатольевич": "https://www.ugrasu.ru/timetable/lecturer/8707",
    "Королькова Елена Александровна": "https://www.ugrasu.ru/timetable/lecturer/5813",
    "Куртханов Тимур Назарович": "https://www.ugrasu.ru/timetable/lecturer/8817",
    "Леонов Алексей Евгеньевич": "https://www.ugrasu.ru/timetable/lecturer/8725",
    "Лукьянова Наталья Анатольевна": "https://www.ugrasu.ru/timetable/lecturer/5681",
    "Лыкова Ольга Ивановна": "https://www.ugrasu.ru/timetable/lecturer/5904",
    "Макаева Гульфия Батыровна": "https://www.ugrasu.ru/timetable/lecturer/5907",
    "Макеева Наталья Васильевна": "https://www.ugrasu.ru/timetable/lecturer/5759",
    "Манакова Светлана Михайловна": "https://www.ugrasu.ru/timetable/lecturer/7771",
    "Марюхина Светлана Валерьевна": "https://www.ugrasu.ru/timetable/lecturer/5852",
    "Милютин Александр Викторович": "https://www.ugrasu.ru/timetable/lecturer/5765",
    "Мухин Антон Валерьевич": "https://www.ugrasu.ru/timetable/lecturer/5920",
    "Нигматуллин Камиль Наильевич": "https://www.ugrasu.ru/timetable/lecturer/5766",
    "Нуриахметова Эльвира Ильгизовна": "https://www.ugrasu.ru/timetable/lecturer/6265",
    "Пальшина Лилия Наилевна": "https://www.ugrasu.ru/timetable/lecturer/5834",
    "Педенко Андрей Николаевич": "https://www.ugrasu.ru/timetable/lecturer/5830",
    "Пожидаева Галина Анатольевна": "https://www.ugrasu.ru/timetable/lecturer/5744",
    "Полухин Денис Иванович": "https://www.ugrasu.ru/timetable/lecturer/6260",
    "Попов Александр Николаевич": "https://www.ugrasu.ru/timetable/lecturer/5752",
    "Портнягин Артём Сергеевич": "https://www.ugrasu.ru/timetable/lecturer/6266",
    "Рахматуллаева Зульфия Закариевна": "https://www.ugrasu.ru/timetable/lecturer/5767",
    "Ребенок Галина Александровна": "https://www.ugrasu.ru/timetable/lecturer/5758",
    "Рева Наиля Юсуповна": "https://www.ugrasu.ru/timetable/lecturer/5874",
    "Савватеева Наталья Ивановна": "https://www.ugrasu.ru/timetable/lecturer/5857",
    "Сагдатдинова Оксана Сабирчановна": "https://www.ugrasu.ru/timetable/lecturer/5898",
    "Сидоров Станислав Вячеславович": "https://www.ugrasu.ru/timetable/lecturer/6247",
    "Тухтахулова Фирзуля Тухтасыновна": "https://www.ugrasu.ru/timetable/lecturer/5784",
    "Тяжельникова Светлана Валерьевна": "https://www.ugrasu.ru/timetable/lecturer/5779",
    "Тяпкова Тамара Владиславовна": "https://www.ugrasu.ru/timetable/lecturer/7770",
    "Федорова Наталия Станиславовна": "https://www.ugrasu.ru/timetable/lecturer/5908",
    "Хафизова Асель Геннадьевна": "https://www.ugrasu.ru/timetable/lecturer/9097",
    "Чупракова Ирина Владимировна": "https://www.ugrasu.ru/timetable/lecturer/2965",
    "Шарипов Наиль Зарифович": "https://www.ugrasu.ru/timetable/lecturer/6272",
    "Шарипова Ирина Александровна": "https://www.ugrasu.ru/timetable/lecturer/5912",
    "Шашко Марина Владимировна": "https://www.ugrasu.ru/timetable/lecturer/5806",
    "Шумейко Димитрий Анатольевич": "https://www.ugrasu.ru/timetable/lecturer/8734",
    "Шумскис Владислав Владиславович": "https://www.ugrasu.ru/timetable/lecturer/5816",
    "Шумскис Юлия Геннадьевна": "https://www.ugrasu.ru/timetable/lecturer/5885",
    "Григорьева Виктория Петровна": "https://www.ugrasu.ru/timetable/lecturer/8898",
    "Исаченко Александр Владимирович": "https://www.ugrasu.ru/timetable/lecturer/8708",
    "Мазуров Сергей Викторович": "https://www.ugrasu.ru/timetable/lecturer/8899",
}

courses = {
    "Курс4": {
        "1БС11": "https://www.ugrasu.ru/timetable/group/8409",
        "1БС12": "https://www.ugrasu.ru/timetable/group/8442",
        "1ИС10": "https://www.ugrasu.ru/timetable/group/8355",
        "1МНЭ11": "https://www.ugrasu.ru/timetable/group/8330",
        "1МНЭ12": "https://www.ugrasu.ru/timetable/group/8331",
        "1РЭ11": "https://www.ugrasu.ru/timetable/group/8468",
        "1РЭ12": "https://www.ugrasu.ru/timetable/group/8495",
        "1РЭ13": "https://www.ugrasu.ru/timetable/group/8496",
    },
    "Курс3": {
        "1ИС22": "https://www.ugrasu.ru/timetable/group/8326",
        "1ИС21": "https://www.ugrasu.ru/timetable/group/8325",
        "1БС20": "https://www.ugrasu.ru/timetable/group/8438",
        "1МНЭ20": "https://www.ugrasu.ru/timetable/group/8354",
        "1МНЭ20п": "https://www.ugrasu.ru/timetable/group/8565",
        "1РЭ21": "https://www.ugrasu.ru/timetable/group/8494",
        "1РЭ22": "https://www.ugrasu.ru/timetable/group/8407",
        "1РЭ23": "https://www.ugrasu.ru/timetable/group/8529",
        "1ЭБ20": "https://www.ugrasu.ru/timetable/group/8439"
    },
    "Курс2": {
        "1БС30": "https://www.ugrasu.ru/timetable/group/8532",
        "1ИС30": "https://www.ugrasu.ru/timetable/group/8406",
        "1ИС30п": "https://www.ugrasu.ru/timetable/group/8441",
        "1МНЭ30": "https://www.ugrasu.ru/timetable/group/8531",
        "1МНЭ30п": "https://www.ugrasu.ru/timetable/group/8467",
        "1МЭ30": "https://www.ugrasu.ru/timetable/group/8437",
        "1РЭ30п": "https://www.ugrasu.ru/timetable/group/8376",
        "1РЭ31": "https://www.ugrasu.ru/timetable/group/8356",
        "1РЭ32": "https://www.ugrasu.ru/timetable/group/8327",
        "1ЭБ30": "https://www.ugrasu.ru/timetable/group/8357"
    },
    "Курс1": {
        "1БС41п": "https://www.ugrasu.ru/timetable/group/8440",
        "1ИС41п": "https://www.ugrasu.ru/timetable/group/8372",
        "1МНЭ41п": "https://www.ugrasu.ru/timetable/group/8374",
        "1МЭ41п": "https://www.ugrasu.ru/timetable/group/8530",
        "1РЭ41": "https://www.ugrasu.ru/timetable/group/8408",
        "1РЭ41п": "https://www.ugrasu.ru/timetable/group/8373",
        "1ЭБ41": "https://www.ugrasu.ru/timetable/group/8329",
        "1ЭСТ41п": "https://www.ugrasu.ru/timetable/group/8375",
        "1ЭСТ42п": "https://www.ugrasu.ru/timetable/group/8328"
    }
}

auditorium = {
    "Этаж 1": {
        "107": "https://www.ugrasu.ru/timetable/auditory/1768",
        "108": "https://www.ugrasu.ru/timetable/auditory/1767",
        "Актовый Зал 113": "https://www.ugrasu.ru/timetable/auditory/1766",
        "124": "https://www.ugrasu.ru/timetable/auditory/1765",
    },
    "Этаж 2": {
        "208": "https://www.ugrasu.ru/timetable/auditory/1763",
        "210": "https://www.ugrasu.ru/timetable/auditory/1762",
        "216": "https://www.ugrasu.ru/timetable/auditory/1761",
        "217": "https://www.ugrasu.ru/timetable/auditory/1760",
        "235": "https://www.ugrasu.ru/timetable/auditory/1758",
        "237": "https://www.ugrasu.ru/timetable/auditory/1759",
    },
    "Этаж 3": {
        "301": "https://www.ugrasu.ru/timetable/auditory/1757",
        "305": "https://www.ugrasu.ru/timetable/auditory/1756",
        "310": "https://www.ugrasu.ru/timetable/auditory/1754",
        "312": "https://www.ugrasu.ru/timetable/auditory/1755",
        "313": "https://www.ugrasu.ru/timetable/auditory/1753",
        "314": "https://www.ugrasu.ru/timetable/auditory/1752",
        "321": "https://www.ugrasu.ru/timetable/auditory/2341",
        "323": "https://www.ugrasu.ru/timetable/auditory/1751",
        "325": "https://www.ugrasu.ru/timetable/auditory/1750",
        "329": "https://www.ugrasu.ru/timetable/auditory/1748",
        "331": "https://www.ugrasu.ru/timetable/auditory/1749",
    },
    "2 корпус": {
        "133": "https://www.ugrasu.ru/timetable/auditory/1746",
        "209": "https://www.ugrasu.ru/timetable/auditory/1743",
        "210": "https://www.ugrasu.ru/timetable/auditory/1742",
        "216": "https://www.ugrasu.ru/timetable/auditory/1740",
    },
    "НКИ": {
        "1204": "https://www.ugrasu.ru/timetable/auditory/1738",
        "1205": "https://www.ugrasu.ru/timetable/auditory/1737",
        "1215": "https://www.ugrasu.ru/timetable/auditory/1736",
        "1216": "https://www.ugrasu.ru/timetable/auditory/1735",
        "1217": "https://www.ugrasu.ru/timetable/auditory/1734",
    },
    "Физ-ра": {
        "СЗ": "https://www.ugrasu.ru/timetable/auditory/2026",
        "Стадион" : "https://www.ugrasu.ru/timetable/auditory/2141"
    }
}
